name: .NET Core # will work, but only show the text and not the value $[env.nameVar] 
# ${{ env.nameVar }} this one will not start

on: 
  push:
    branches: [main]
  workflow_dispatch:
    
env:
  nameVar: "test"

jobs:
  build:
    #name: Testing with ${{ env.nameVar }} this one will not start
    environment: Production

    runs-on: ubuntu-latest

    steps:
    - run: echo "GITHUB_WORKFLOW=Workflow name from step" >> $GITHUB_ENV

    - uses: actions/checkout@v3

    - name: Setup .NET Core    
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    # dotnet build and publish
    - name: Build with dotnet ${{ env.nameVar }}
      run: |
        dotnet build --configuration Release ./dotnet-core-webapp/dotnetcore-webapp.csproj
      
    - name: dotnet publish
      run: |
        dotnet publish -c Release -o dotnetcorewebapp ./dotnet-core-webapp
    - name: upload Artificat
      uses: actions/upload-artifact@v4.0.0
      with:
        name: artifact
        path: ./dotnet-core-webapp
        
    # test for usage in versioning
    - name: Hello world
      run: echo Hello world, run number = $NBR
      env: 
        NBR: ${{ github.RUN_NUMBER }}

  Download:
    needs: build
    runs-on: windows-latest
    name: Download Artifact
    steps:
    - name: Download
      uses: actions/download-artifact@v4.1.0
      with:
        name: artifact
        path: ./dotnet-core-webapp

  webtest:

    runs-on: windows-latest
    needs: [build, Download]

    steps:
    - uses: actions/checkout@v3

    - name: Run Web Test
      run: |
        # overwrite the AppSettings.json
        #$pathToFile = "./dotnet-core-webapp.webtests/AppSettings.json"
        #$fileContent = Get-Content $pathToFile
        #$fileContent = $fileContent.Replace("http://localhost/dotnetcore-webapp/", "https://dotnetcorewebapp19.azurewebsites.net/")
        #Set-Content $pathToFile $fileContent

        # build the test project
        dotnet build --configuration Release ./dotnet-core-webapp.webtests
        cd ./dotnet-core-webapp.webtests

        # execute the tests
        dotnet test -l:trx

